### PR TITLE
Update class.discussionpollsmodel.php to fix persistence of HTML characters

### PR DESCRIPTION
**Pull request by brandonprry**
Currently, you can save polls with HTML/Javascript in them which will be rendered to the screen when viewed.

This patch updates the model so that data persisted has been sanitized. Does not address previously saved polls with bad data in it. Not sure the best way to solve this.

### CODE REVIEW

**Comment by hgtonight** [comment]
Thanks for the PR!

Mind switching to using `Gdn_Format::Text()` instead of `htmlspecialchars()`?

Update that and I will merge immediately. :)

**Comment by brandonprry** [comment]
Sure thing.

On Thu, Mar 26, 2015 at 8:12 AM, Zachary Doll <notifications@github.com>
wrote:

> Thanks for the PR!
>
> Mind switching to using Gdn_Format::Text() instead of htmlspecialchars()?
>
> Update that and I will merge immediately. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hgtonight/Plugin-DiscussionPolls/pull/2#issuecomment-86507792>
> .
>



-- 
http://volatile-minds.blogspot.com -- blog
http://www.volatileminds.net -- website

**Comment by brandonprry** [comment]
When this gets pushed, will the package on the Vanilla community site get updated as well?

**Comment by hgtonight** [comment]
Not automatically, but I will update it there.

**Comment by brandonprry** [comment]
Thanks a bunch dude!

**Comment by hgtonight** [comment]
Thanks for the PR :)

**Pull request merged**
